package com.sdtv.trident.common

enum class OtpEnumClass {
    INIT,
    ERROR,
    LOADING,
    SUCCESS,
    CHANGE_COLOR,
    FIRST_EDITTEXT,
    SECOND_EDITTEXT,
    THIRD_EDITTEXT,
    FORTH_EDITTEXT,
    FIFTH_EDITTEXT,
    SIXTH_EDITTEXT,
    SERVER_ERROR,
    EMAILERROR,
    PASSWORD_ERROR,
    BACKGROUND_BUTTON,
    TOAST_MESSAGE
}